<?php
namespace backend\components;

use Yii;
use yii\web\Controller;

class BaseController extends Controller
{

    public function beforeAction($action)
    {
        //var_dump(Yii::$app->user->isGuest);die;
        if(Yii::$app->user->isGuest)
        {
            //return $this->redirect(['site/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}